from odoo import models, fields


class ClientProfile(models.Model):
    _name = 'client.profile'
    _description = "Profile"
    # profile
    is_company = fields.Selection([('individual', 'Individual'), ('company', 'Company')])
    name = fields.Char(string="Client Name", required=True)
    image = fields.Image(string="Image")
    organization_type = fields.Many2one(comodel_name="res.partner", string="Organization Type")
    industry_class = fields.Many2one(comodel_name="res.partner", string="Industry Class")
    nature_of_business = fields.Text(string="Nature of Business")
    date_of_engagement = fields.Date('date')
    client_id = fields.Char(string="Client ID")
    tax_reporting_compliance = fields.Boolean(string="Tax Reporting & Compliance")
    annual_registration_update = fields.Boolean(string="Annual Registration Update")
    agree_upon_procedure = fields.Boolean(string="Agree-Upon Procedures")
    audit_assurance = fields.Boolean(string="Audit & Assurance")
    tax_advocacy = fields.Boolean(string="Tax Advocacy(Investigation)")
    advisory_consultancy = fields.Boolean(string="Advisory & Consultancy")
    compilation = fields.Boolean(string="Compilation")
    others = fields.Char(string="Others")
    # Contacts
    unit_no = fields.Char(string="Unit/Floor")
    building_name = fields.Char(string="Building Name")
    street = fields.Char(string="Street")
    district = fields.Char(string="District/Barangay/Village")
    city = fields.Char(string="City")
    zip = fields.Char(string="Zip Code")
    landline = fields.Char(string="Telephone")
    website = fields.Char(string="Website")
    unit_no2 = fields.Char(string="Unit/Floor")
    building_name2 = fields.Char(string="Building Name")
    street2 = fields.Char(string="Street")
    district2 = fields.Char(string="District/Barangay/Village")
    city2 = fields.Char(string="City")
    zip2 = fields.Char(string="Zip Code")
    landline2 = fields.Char(string="Telephone")
    primary_contact_person = fields.Char(string="Primary Contact")
    mobile_no = fields.Char(string="Mobile No.")
    email_address = fields.Char(string="Email Address")
    principal_accounting_officer = fields.Char(string="Principal Accounting Officer")
    landline3 = fields.Char(string="Telephone")
    mobile_no2 = fields.Char(string="Mobile No.")
    email_address2 = fields.Char(string="Email Address")
    corporate_ids = fields.One2many(comodel_name='corporate.officer', inverse_name='client_profile_ids',
                                    string="Officer")
    # BIR
    vat = fields.Char(string="Tax Id No.")
    rdo_code = fields.Char(string="RDO Code")
    registration_date = fields.Date('Date')
    income_tax = fields.Boolean(string="Income Tax")
    excise_tax = fields.Boolean(string="Excise Tax")
    value_added_tax = fields.Boolean(string="Value-added Tax")
    withholding_tax_expanded = fields.Boolean(string="Withholding Tax-Expanded")
    withholding_tax_compensation = fields.Boolean(string="Withholding Tax-Compensation")
    registration_fee = fields.Boolean(string="Registration Fee")
    other_percentage_tax = fields.Char(string="Other Percentage Tax")
    tax_type = fields.Char(string="Taxpayer Type")
    invoice_tax = fields.Char(string="Invoice Type")
    filing_payment = fields.Char(string="Filling & Payment")
    books_of_account = fields.Char(string="Books of Accounts")
    psic_psoc = fields.Char(string="PSIC/PSOC")
    ll_cas_permit_no = fields.Char(string="LL/CAS Permit No")
    ask = fields.Selection([('yes', 'Yes'), ('no', 'No')])
    # SEC/DTI
    registration_number = fields.Char(string="Registration No")
    registration_date_sec = fields.Date('Date')
    trade_name = fields.Char(string="Trade Name")
    date_per_law = fields.Char(string="Date per By-Laws")
    actual_date_meeting = fields.Date('date')
    ask_1 = fields.Selection([('yes', 'Yes'), ('no', 'No')])
    ask_2 = fields.Char(string="If Yes what type of security is the Company permit to sell?")
    class_shares_id = fields.One2many(comodel_name='class.of.shares', inverse_name='client_share_ids', string="Class")
    # Regulatory
    ask_3 = fields.Selection([('yes', 'Yes'), ('no', 'No')])
    bureau_of_custom = fields.Boolean(string="Bureau of Custom")
    bangko_sentral_pilipinas = fields.Boolean(string="Bangko Sentral ng Pilipinas")
    professional_regulation_commission = fields.Boolean(string="Professional Regulation Commission")
    philippines_council_ngo_certification = fields.Boolean(string="Philippine Council for NGO Certification")
    cooperative_development_authority = fields.Boolean(string="Cooperative Development Authority")
    insurance_commission = fields.Boolean(string="Insurance Commission")
    integrated_bar_philippines = fields.Boolean(string="Integrated Bar of the Philippines")
    philippines_stock_exchange = fields.Boolean(string="Philippine Stock Exchange")
    construction_industry_authority_philippines = fields.Boolean(
        string="Construction Industry authority of the Philippines(PCAB)")
    philippine_amusement_gaming_corporation = fields.Boolean(string="Philippine Amusement and Gaming Corporation")
    land_transportation_franchising_regulatory_board = fields.Boolean(
        string="Land Transportation Franchising and Regulatory Board")
    others_ri = fields.Char(string="Others")
    # SSS
    sss = fields.Char(string="SSS ER No")
    phic = fields.Char(string="PHIC ER No")
    hdmf = fields.Char(string="HDMF ER No")
    sss_filing = fields.Char(string="Filing")
    phic_filing = fields.Char(string="Filing")
    hdmf_filing = fields.Char(string="Filing")
    sss_pay = fields.Char(string="Payment")
    phic_pay = fields.Char(string="Payment")
    hdmf_pay = fields.Char(string="Payment")
    # Escalation
    escalation = fields.One2many(comodel_name='escalation.contact', inverse_name='escalation_id',
                                 string="Escalation Point")
